# CtrlP plugins
#
# Maintainer:   DeaR <nayuri@kuonn.mydns.jp>
# Last Change:  18-May-2016.
# License:      MIT License {{{
#     Copyright (c) 2013 DeaR <nayuri@kuonn.mydns.jp>
#
#     Permission is hereby granted, free of charge, to any person obtaining a
#     copy of this software and associated documentation files (the
#     "Software"), to deal in the Software without restriction, including
#     without limitation the rights to use, copy, modify, merge, publish,
#     distribute, sublicense, and/or sell copies of the Software, and to permit
#     persons to whom the Software is furnished to do so, subject to the
#     following conditions:
#
#     The above copyright notice and this permission notice shall be included
#     in all copies or substantial portions of the Software.
#
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#     OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#     MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#     IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#     CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
#     OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
#     THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# }}}

#------------------------------------------------------------------------------
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_cmd = ['CtrlP', 'CtrlPMRUFiles', 'CtrlPBuffer', 'CtrlPLastMode', 'CtrlPClearCache', 'CtrlPClearAllCaches', 'ClearCtrlPCache', 'ClearAllCtrlPCaches', 'CtrlPCurWD', 'CtrlPCurFile', 'CtrlPRoot', 'CtrlPTag', 'CtrlPQuickfix', 'CtrlPDir', 'CtrlPBufTag', 'CtrlPBufTagAll', 'CtrlPRTS', 'CtrlPUndo', 'CtrlPLine', 'CtrlPChange', 'CtrlPChangeAll', 'CtrlPMixed', 'CtrlPBookmarkDir', 'CtrlPBookmarkDirAdd']
on_if = 'empty(&buftype)'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'kshenoy/vim-ctrlp-args'
on_cmd = 'CtrlPArgs'
depends = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'DeaR/ctrlp-chdir'
on_cmd = ['CtrlPChdir', 'CtrlPLchdir']
depends = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'hara/ctrlp-colorscheme'
depends = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'naquad/ctrlp-filetype'
on_cmd = 'CtrlPFileType'
depends = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'zeero/vim-ctrlp-help'
on_cmd = 'CtrlPHelp'
depends = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'DeaR/ctrlp-J6uil'
on_cmd = ['CtrlPJ6uilRooms', 'CtrlPJ6uilMembers']
depends = ['ctrlp', 'J6uil']

#------------------------------------------------------------------------------
[[plugins]]
repo = 'DeaR/ctrlp-jumps'
on_cmd = 'CtrlPJump'
depends = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'ompugao/ctrlp-locate'
on_cmd = 'CtrlPLocate'
depends = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'DeaR/ctrlp-location-list'
on_cmd = ['CtrlPLocList', 'CtrlPLocListAll']
depends = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'mattn/ctrlp-mark'
on_cmd = 'CtrlPMark'
depends = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'FelikZ/ctrlp-py-matcher'
if = 'has("python") || has("python3")'
on_source = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'mattn/ctrlp-register'
on_cmd = 'CtrlPRegister'
depends = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'DeaR/ctrlp-tabpage'
on_cmd = 'CtrlPTabpage'
depends = 'ctrlp'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'mattn/ctrlp-vimpatches'
on_cmd = 'CtrlPVimPatches'
depends = ['ctrlp', 'webapi']

#------------------------------------------------------------------------------
[[plugins]]
repo = 'DeaR/ctrlp-window'
on_cmd = ['CtrlPWindow', 'CtrlPWindowAll']
depends = 'ctrlp'
