# Operator plugins
#
# Maintainer:   DeaR <nayuri@kuonn.mydns.jp>
# Last Change:  01-Jun-2016.
# License:      MIT License {{{
#     Copyright (c) 2013 DeaR <nayuri@kuonn.mydns.jp>
#
#     Permission is hereby granted, free of charge, to any person obtaining a
#     copy of this software and associated documentation files (the
#     "Software"), to deal in the Software without restriction, including
#     without limitation the rights to use, copy, modify, merge, publish,
#     distribute, sublicense, and/or sell copies of the Software, and to permit
#     persons to whom the Software is furnished to do so, subject to the
#     following conditions:
#
#     The above copyright notice and this permission notice shall be included
#     in all copies or substantial portions of the Software.
#
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#     OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#     MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#     IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#     CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
#     OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
#     THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# }}}

#------------------------------------------------------------------------------
[[plugins]]
repo = 'pekepeke/vim-csvutil'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'tyru/operator-camelize.vim'
on_map = [['nov', '<Plug>'], ['nov', '<Plug>(operator-decamelize']]
depends = 'operator-user'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'tyru/operator-html-escape.vim'
on_map = [['nov', '<Plug>'], ['nov', '<Plug>(operator-html-unescape']]
depends = 'operator-user'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'rhysd/vim-operator-filled-with-blank'
on_map = [['nov', '<Plug>']]
depends = 'operator-user'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'syngan/vim-operator-furround'
on_map = [['nov', '<Plug>']]
depends = ['operator-user', 'textobj-multiblock']

#------------------------------------------------------------------------------
[[plugins]]
repo = 'sgur/vim-operator-openbrowser'
on_map = [['nov', '<Plug>']]
depends = ['open-browser', 'operator-user']

#------------------------------------------------------------------------------
[[plugins]]
repo = 'kana/vim-operator-replace'
on_map = [['nov', '<Plug>']]
depends = 'operator-user'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'tyru/operator-reverse.vim'
on_cmd = 'OperatorReverseLines'
on_map = [['nov', '<Plug>']]
depends = 'operator-user'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'osyo-manga/vim-operator-search'
on_map = [['nov', '<Plug>']]
depends = 'operator-user'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-operator-sequence'
on_func = 'operator#sequence#map'
depends = 'operator-camelize'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'pekepeke/vim-operator-shuffle'
on_map = [['nov', '<Plug>']]
depends = 'operator-user'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'emonkak/vim-operator-sort'
on_map = [['nov', '<Plug>']]
depends = 'operator-user'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'tyru/operator-star.vim'
on_map = [['nov', '<Plug>(operator-*', '<Plug>(operator-#', '<Plug>(operator-g*', '<Plug>(operator-g#']]
depends = ['operator-user', 'visualstar']

#------------------------------------------------------------------------------
[[plugins]]
repo = 'yomi322/vim-operator-suddendeath'
on_map = [['nov', '<Plug>']]
depends = 'operator-user'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'pekepeke/vim-operator-tabular'
on_map = [['nov', '<Plug>'], ['nov', '<Plug>(operator-untabularize']]
depends = ['csvutil', 'operator-user']

#------------------------------------------------------------------------------
[[plugins]]
repo = 'rhysd/vim-operator-trailingspace-killer'
on_map = [['nov', '<Plug>']]
depends = 'operator-user'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'kana/vim-operator-user'
on_map = [['nov', '<Plug>(operator']]
on_func = ['operator#user#define', 'operator#user#define_ex_command', 'operator#user#register', 'operator#user#visual_command_from_wise_name']
