# Syntax plugins
#
# Maintainer:   DeaR <nayuri@kuonn.mydns.jp>
# Last Change:  11-May-2016.
# License:      MIT License {{{
#     Copyright (c) 2016 DeaR <nayuri@kuonn.mydns.jp>
#
#     Permission is hereby granted, free of charge, to any person obtaining a
#     copy of this software and associated documentation files (the
#     "Software"), to deal in the Software without restriction, including
#     without limitation the rights to use, copy, modify, merge, publish,
#     distribute, sublicense, and/or sell copies of the Software, and to permit
#     persons to whom the Software is furnished to do so, subject to the
#     following conditions:
#
#     The above copyright notice and this permission notice shall be included
#     in all copies or substantial portions of the Software.
#
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#     OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#     MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#     IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#     CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
#     OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
#     THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# }}}

#------------------------------------------------------------------------------
[[plugins]]
repo = 'ARM9/arm-syntax-vim'
# on_ft = ['arm', 'armv4', 'armv5']
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo ='vim-jp/cpp-vim'
# on_ft = ['c', 'ch', 'cpp', 'cuda', 'cynlib', 'cynpp', 'dtrace', 'esqlc', 'kwt', 'objc', 'objcpp', 'rpcgen', 'splint', 'xs']
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'JulesWang/css.vim'
# on_ft = ['aspperl', 'aspvbs', 'cf', 'css', 'dtml', 'groovy', 'gsp', 'haml', 'html', 'htmlcheetah', 'htmldjango', 'htmlm4', 'htmlos', 'jsp', 'markdown', 'mason', 'msql', 'php', 'plp', 'phtml', 'sass', 'scss', 'smarty', 'spyce', 'tt2html', 'webmacro', 'wml', 'xhtml']
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
# on_ft = ['aspperl', 'aspvbs', 'cf', 'css', 'dtml', 'groovy', 'gsp', 'haml', 'html', 'htmlcheetah', 'htmldjango', 'htmlm4', 'htmlos', 'jsp', 'markdown', 'mason', 'msql', 'php', 'plp', 'phtml', 'sass', 'scss', 'smarty', 'spyce', 'tt2html', 'webmacro', 'wml', 'xhtml']
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'JesseKPhillips/d.vim'
# on_ft = 'd'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-ft-diff_fold'
# on_ft = 'diff'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'google/vim-ft-go'
# on_ft = 'go'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-ft-help_fold'
# on_ft = 'help'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-ft-markdown_fold'
# on_ft = 'markdown'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-ft-vim_fold'
# on_ft = 'vim'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'othree/html5.vim'
# on_ft = ['aspperl', 'aspvbs', 'cf', 'dtml', 'eruby', 'groovy', 'gsp', 'haml', 'html', 'htmlcheetah', 'htmldjango', 'htmlm4', 'htmlos', 'javascript', 'jsp', 'liquid', 'markdown', 'mason', 'msql', 'php', 'phtml', 'plp', 'smarty', 'spyce', 'tt2html', 'tt2js', 'webmacro', 'wml', 'xhtml']
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'HybridText'
# on_ft = ['hybrid', 'text']
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'jelera/vim-javascript-syntax'
# on_ft = ['javascript', 'tt2js']
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'elzr/vim-json'
# on_ft = 'json'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'januswel/dotfiles'
name = 'mayu'
rtp = '.vim'
# on_ft = 'mayu'
lazy = 0
build = '~/.vim/dein/script/mayu/build'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'evanmiller/nginx-vim-syntax'
# on_ft = 'nginx'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-perl/vim-perl'
# on_ft = ['perl', 'perl6', 'pod', 'tt2', 'tt2html', 'tt2js', 'xs']
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'
name = 'PHP-Indenting'
# on_ft = 'php'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'PProvost/vim-ps1'
# on_ft = ['ps1', 'ps1xml']
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-ruby/vim-ruby'
# on_ft = ['eruby', 'haml', 'ruby']
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'jiangmiao/simple-javascript-indenter'
# on_ft = 'javascript'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'tyru/skkdict.vim'
# on_ft = 'skkdict'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-jp/syntax-vim-ex'
# on_ft = 'vim'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'zaiste/tmux.vim'
# on_ft = 'tmux'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'cespare/vim-toml'
# on_ft = 'toml'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'vbnet.vim'
# on_ft = 'vbnet'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'chrisbra/vim-zsh'
# on_ft = 'zsh'
lazy = 0
