# Syntax plugins
#
# Maintainer:   DeaR <nayuri@kuonn.mydns.jp>
# Last Change:  31-Oct-2017.
# License:      MIT License {{{
#     Copyright (c) 2013 DeaR <nayuri@kuonn.mydns.jp>
#
#     Permission is hereby granted, free of charge, to any person obtaining a
#     copy of this software and associated documentation files (the
#     "Software"), to deal in the Software without restriction, including
#     without limitation the rights to use, copy, modify, merge, publish,
#     distribute, sublicense, and/or sell copies of the Software, and to permit
#     persons to whom the Software is furnished to do so, subject to the
#     following conditions:
#
#     The above copyright notice and this permission notice shall be included
#     in all copies or substantial portions of the Software.
#
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
#     OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
#     MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
#     IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
#     CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT
#     OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
#     THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# }}}

#------------------------------------------------------------------------------
[[plugins]]
repo = 'ARM9/arm-syntax-vim'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-jp/cpp-vim'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'JulesWang/css.vim'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'JesseKPhillips/d.vim'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-ft-diff_fold'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-scripts/dosbatch-indent'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'google/vim-ft-go'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-ft-help_fold'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-ft-markdown_fold'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'thinca/vim-ft-vim_fold'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'othree/html5.vim'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-scripts/HybridText'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'pangloss/vim-javascript'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'elzr/vim-json'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'januswel/dotfiles'
name = 'mayu'
rtp = '.vim'
lazy = 0
build = '~/.vim/dein/script/mayu/build'

#------------------------------------------------------------------------------
[[plugins]]
repo = 'chr4/nginx.vim'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-perl/vim-perl'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = '2072/PHP-Indenting-for-VIm'
name = 'PHP-Indenting'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'PProvost/vim-ps1'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-ruby/vim-ruby'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'tyru/skkdict.vim'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'vim-jp/syntax-vim-ex'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'zaiste/tmux.vim'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'cespare/vim-toml'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'Eivy/vim-vbnet'
lazy = 0

#------------------------------------------------------------------------------
[[plugins]]
repo = 'chrisbra/vim-zsh'
lazy = 0
